#!/bin/bash

TOP_LEVEL_UTILS="losf node_types rpm_topdir sync_config_files update update.sh update_hosts"

for i in $TOP_LEVEL_UTILS ; do
    ./update_license.pl ../LICENSE ../$i
done

for i in `ls ../utils/*.pm`; do 
    ./update_license.pl ../LICENSE $i
done

for i in `ls ../utils/*.pl`; do 
    ./update_license.pl ../LICENSE $i
done


