#!/bin/bash

# Simple convenience utility to update headers. Skip soft links.

TOP_LEVEL_UTILS="losf node_types rpm_topdir sync_config_files update update update_hosts initconfig"

for i in $TOP_LEVEL_UTILS ; do
    if [ ! -L ../$i ];then
	./update_license.pl ../LICENSE ../$i
    fi
done

for i in `ls ../utils/*.pm`; do 
    if [ ! -h ../utils/$i ];then
	./update_license.pl ../LICENSE $i
    fi
done

for i in `ls ../utils/*.pl`; do 
    if [ ! -L ../utils/$i ];then
	./update_license.pl ../LICENSE $i
    fi
done


for i in `ls ../misc/config_latest_install`; do 
    if [ ! -h ../misc/$i ];then
	./update_license.pl ../LICENSE $i
    fi
done