#!/bin/bash
#-----------------------------------------------------------------------bl-
#--------------------------------------------------------------------------
# 
# LosF - a Linux operating system Framework for HPC clusters
#
# Copyright (C) 2007-2014 Karl W. Schulz <losf@koomie.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Version 2 GNU General
# Public License as published by the Free Software Foundation.
#
# These programs are distributed in the hope that they will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc. 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------el-
# Shell wrapper for querying local node type -> echo's config to stdout
#--------------------------------------------------------------------------

# determine path to binary
[[ -L $0 ]] && binary=`readlink -f $0` || binary=$0

# disable colors for non-interactive shell
[[ ! -t 1 ]] && export ANSI_COLORS_DISABLED=1

export TOP_DIR=`echo $( (cd -P $(dirname $binary) && pwd) )`

if [  -z $PERL5LIB ];then
    export PERL5LIB=$TOP_DIR/utils
else
    export PERL5LIB=$TOP_DIR/utils:$PERL5LIB
fi

export LOSF_LOG_MODE="INFO"
export LOSF_STANDALONE_UTIL=1

if [ $# -ge 1 ];then
    export LOSF_NODE_TYPE_REGEX_QUERY=1
else
    unset LOSF_NODE_TYPE_REGEX_QUERY
fi


$TOP_DIR/utils/node_types.pl "$@"
