#!/bin/bash
#-----------------------------------------------------------------------bl-
#--------------------------------------------------------------------------
# 
# LosF - a Linux operating system Framework for HPC clusters
#
# Copyright (C) 2007-2012 Karl W. Schulz
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Version 2 GNU General
# Public License as published by the Free Software Foundation.
#
# These programs are distributed in the hope that they will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc. 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------el-
#
# Wrapper for file syncing utilitity.
#
# $Id$
#--------------------------------------------------------------------------

export TOP_DIR=`echo $( (cd -P $(dirname $0) && pwd) )`
export PERL5LIB=$TOP_DIR/utils

if [ $# -eq 0 ];then
    $TOP_DIR/utils/sync_config.pl
elif [ $# -eq 1 ];then
    $TOP_DIR/utils/sync_named_file.pl $1
#    echo "??"
else
#    echo "[Warn]: Ignoring extra command-line arguments"
    echo " "
    echo "Usage: sync_config_files <individual-file>"
    echo " "
    exit 1
fi


