#!/bin/bash
#-----------------------------------------------------------------------bl-
#--------------------------------------------------------------------------
# 
# LosF - a Linux operating system Framework for HPC clusters
#
# Copyright (C) 2007-2013 Karl W. Schulz
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Version 2 GNU General
# Public License as published by the Free Software Foundation.
#
# These programs are distributed in the hope that they will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc. 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301  USA
#
#-----------------------------------------------------------------------el-
# Wrapper for updating local host file 
#--------------------------------------------------------------------------

if [ -h $0 ];then
    echo "Running from a soft link"
    export TOP_DIR=`dirname $(readlink -f ${0})`
else
    export TOP_DIR=`echo $( (cd -P $(dirname $0) && pwd) )`
fi

if [  -z $PERL5LIB ];then
    export PERL5LIB=$TOP_DIR/utils
else
    export PERL5LIB=$TOP_DIR/utils:$PERL5LIB
fi

if [ ! -e $TOP_DIR/utils/update_hosts.pl ]; then
    echo "[Error]: unable to locate update_hosts.pl"]
    exit 1
fi

$TOP_DIR/utils/update_hosts.pl
