#!/bin/bash

#echo
#echo "cmd: ipmitool -I lan -H $1 -U root chassis bootdev pxe"
#echo

if [ ! $IPMI_PASSWORD ]
then
stty -echo
read -p "Password: " passw; echo
stty echo
echo
/usr/bin/ipmitool -I lan -H $1 -U root -P $passw chassis bootdev pxe
echo
fi

if [ $IPMI_PASSWORD ]
then
  /usr/bin/ipmitool -E -I lan -H $1 -U root chassis bootdev pxe
fi

exit 0
