#!/bin/bash
#
# $Id$
#

if [ $# -lt 1 ];then
    echo " "
    echo "Usage: ipxe host1 [host2 host3 ...]"
    echo " "
    exit 1
fi

# Get password if necessary

if [ ! $IPMI_PASSWORD ]; then
    stty -echo
    read -p "Password: " passw; echo
    stty echo
#    echo
#    /usr/bin/ipmitool -I lan -H $1 -U root -P $passw chassis bootdev pxe
#    echo
fi

# Do the deed for all requested hosts

while (( "$#" )) ; do 

    if [ $IPMI_PASSWORD ]; then
	/usr/bin/ipmitool -E -I lan -H $1 -U root chassis bootdev pxe
    else
	/usr/bin/ipmitool -I lan -H $1 -U root -P $passw chassis bootdev pxe
    fi

    shift
done

exit 0
