#!/bin/bash

if [ ! $IPMI_PASSWORD ]; then
    stty -echo
    read -p "Password: " passw; echo
    stty echo
    echo

    /usr/bin/ipmitool -I lan -H $1 -U root -P $passw chassis power soft
    echo
fi

# ks mod: 4/28/08 - allow for multiple command-line hosts
# 

NUM_HOSTS=$#

if [ $IPMI_PASSWORD ]; then
    for host in `seq 1 $NUM_HOSTS`; do
	myhost=$1 
	printf "$myhost: "
	/usr/bin/ipmitool -E -I lan -H $myhost -U root chassis power soft
	shift
    done
fi

exit 0
